### ISSUE TITLE
Add more unit tests 

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/ClassicalMaximals#15]
You already added some tests (good!) but there more functions that IMHO should have some basic tests to verify they return correct results. E.g. for
- [x] `SolveFrobeniusEquation`
- [x] `OddExtraspecialNormalizerInGL`
- [x] `SymplecticTypeNormalizerInGL`
- ... more to be added, see e.g. the coverage reports on https://app.codecov.io/gh/ssiccha/ClassicalMaximals/blob/main/gap/ReducibleMatrixGroups.gi and https://app.codecov.io/gh/ssiccha/ClassicalMaximals/blob/main/gap/ClassicalMaximals.gi

**Comment by maxhauck** [comment]
The two functions concerning extraspecial groups you listed are actually covered by the tests (as seen here: https://app.codecov.io/gh/ssiccha/ClassicalMaximals/blob/main/gap/ExtraspecialNormalizerMatrixGroups.gi); it's just that they are not tested explicitly as they are only "local" functions, but rather implicitly by being called by other "global" functions that are actually tested. - Are you suggesting we should turn these into "global" functions in order to be able to test them explicitly?

**Comment by fingolfin** [comment]
Short version: yes, add separate tests for these, but there is no need to turn these into "global" functions for that.

Long version: First off, tests (and also users) can call any function, the "global" stuff just makes them read-only (but even that can be undone), and sometimes "DeclareGlobalFunction" is useful (e.g. for mutually recursive functions, and so on), but in general these are purely optional.

Moreover, code coverage is a "necessary" but not sufficient measure. By only testing these function indirectly, you are likely to not test them comprehensively. The idea with "unit tests" is to test each code unit with a well-defined interface separately, to see if it conforms with the "contract" laid out in its documentation or comments - which hopefully are there, to define what it is supposed to do -- of course in practice, this may only exist in the heads of the people who wrote the code (bad!! write it up!!!), but that makes it even more important to codify the API via tests, also to be able to quickly test future changes to it. Like, suppose I have a much better algorithm for `SolveFrobeniusEquation` and I put it in. But because I don't know your hidden assumption, my version accidentally diverges in some corner cases from the old one; and the tests which only indirectly called `SolveFrobeniusEquation` may never reach these corner cases -- but perhaps some happless endusers half a year later triggers it...

**Comment by maxhauck** [comment]
Just adding a checklist to track this :)

In `Utils.gi`:
- [ ] `MatrixByEntries`
- [ ] `AntidiagonalMat`
- [ ] `SolveQuadraticCongruence`
- [ ] `ApplyFunctionToEntries`
- [ ] `HermitianConjugate`
- [ ] `SolveFrobeniusEquation`
- [ ] `QuoCeil`
- [ ] `ReflectionMatrix`
- [ ] `GeneratorsOfOrthogonalGroup`
In `Forms.gi`:
- [ ] `ChangeFixedSesquilinearForm`
- [ ] `ConjugateToStandardForm`
- [ ] `UnitaryForm`
In `SemilinearMatrixGroups.gi`:
- [ ] `GammaLDimension1`
In `ExtraspecialNormalizerMatrixGroups.gi`:
- [ ] `OddExtraspecialGroup`
- [ ] `OddExtraspecialNormalizerInGL`
- [ ] `SymplecticTypeNormalizerInGL`
- [ ] `Extraspecial2MinusTypeNormalizerInGL`
