### ISSUE TITLE
Use `InvariantXForm`

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/ClassicalMaximals#24]
When working with the forms left invariant by our classical groups, do not rely on the forms always being as documented in Section `50.2 Classical Groups` of the GAP reference manual. Instead use the there referenced functions `InvariantXForm` and our utility function `ChangeInvariantSesquilinearForm` (can't currently work with quadratic forms).

**Comment by maxhauck** [comment]
I have written a function for that: `ConjugateToGAPForm`, see my PR #20. 

It works for all cases except orthogonal groups in characteristic 2 as of yet; for symplectic and orthogonal groups, the argument `group` needs the attribute `InvariantBilinearForm`, for unitary groups, this is not required (as the preserved unitary form is automatically recognised if needed).
