### ISSUE TITLE
Use `ClassicalForms_InvariantFormFrobenius`?

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/ClassicalMaximals#25]
instead of `PreservedSesquilinearForms`? Would that work? I have no idea what it does. Maybe it works and using it would be easier. We'll need that when we do the C3 Class for the unitary, probably for the others which respect a non-trivial form too.

**Comment by fingolfin** [comment]
You are not using `PreservedSesquilinearForms` right now at all, though? I feel as if this issue is missing some context?

**Comment by maxhauck** [comment]
Use `ConjugateToStandardForm`, cf. #24.
