### ISSUE TITLE
How to review and test

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/ClassicalMaximals#26]
During today's recog call @AnnaKDS @danielrademacher @maxhauck and I collected some ideas about how we should review PRs on this repo. We certainly don't want to follow and understand every construction step by step because that's a lot of work. If we wanted to be that thorough, I'd rather suggest to always do pair programming to make sure we're not misunderstanding any of the constructions.

However, I think the following should be a good plan. I've added a template in #27.

What do you think, @fingolfin?

**Comment by ssiccha** [comment]
See #27.

**Comment by fingolfin** [comment]
Sure, fine by me

**Comment by ssiccha** [comment]
Fixed by #27. We'll review according to that.
