### ISSUE TITLE
CI: fetch newest version of recog

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/ClassicalMaximals#28]
We want to use recog in our test suite. Hence we should update the GitHub CI Action to always fetch the latest recog version.

**Comment by fingolfin** [comment]
I believe this was resolved by @danielrademacher in commit 8f59674fe1cd1c1449e36c2edd6580061e24d18c ? Can this be closed then?

**Comment by ssiccha** [comment]
Yepp.
