### ISSUE TITLE
Does Magma use the same Conway polynomials?

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/ClassicalMaximals#3]
Is `$.1` in Magma the same as e.g. `Z(25)` in GAP?

**Comment by fingolfin** [comment]
I think you got confused here: Conway polynomials are uniquely defined. I think your question is: do they always use Conway polynomials to define all finite fields? The answer is no, just like GAP doesn't always do this; but in many cases both do. We can talk about it, but I am typing on a phone now

**Comment by fingolfin** [comment]
I am not sure what the issue here is supposed to be, so I'll close this.
