### ISSUE TITLE
Does BaseChangeHomomorphism transfer sizes etc.

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/ClassicalMaximals#66]
In `ChangeFixedSesquilinearForm` we apply a `BaseChangeHomomorphism` and then do `SetSize`. Doesn't a `BaseChangeHomomorphism` transfer this knowledge to its image automatically?

**Comment by fingolfin** [comment]
The code is now using `UseIsomorphismRelation`, and PR #124 removes the only two uses of `BaseChangeHomomorphism `, so this issue is resolved.
